name: Build and publish

on:
  push:
    branches: [main]
    tags:
      - v*.*.*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: zip -r dev.stenz.http.zip ./build/dev.stenz.http
      - uses: actions/upload-artifact@v4
        with:
          name: dev.stenz.http.zip
          path: dev.stenz.http.zip
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          artifacts: dev.stenz.http.zip
          token: ${{ secrets.GITHUB_TOKEN }}